### ISSUE TITLE
signup page

### ISSUE THREAD

**Issue by rdezic276** [rdezic276/SwensonBBQ#6]
submit button needs to have color and formatting of the button and "password must include", need to match the rest of the page. Same thing for Login Page.

**Comment by rhovey15** [comment]
The sign up and the login pages have both been tweaked so the form looks better. I added some style to the submit button, just have a little issue I will ask Craven about.

**Comment by rhovey15** [comment]
Issue resolved, arrow is appearing on the submit button.
